development:
  adapter: postgresql
  database: energy_news_scraper_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: energy_news_scraper_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: energy_news_scraper_production
  pool: 5
  timeout: 5000
